### ISSUE TITLE
Jar shakes when clicked anywhere on page

### ISSUE THREAD

**Issue by jgvargas** [jgvargas/2022-Cohort-Projects#22]
The jar image seems to shake when a click happens anywhere on the page. The buttons extend for some reason too.. interesting

**Comment by clintonmyers** [comment]
The animation takes the animated element out of the flow of the page with position: absolute, and the buttons therefore take up the space that opened up as the jar is essentially gone as far as the buttons are concerned. The animated element should be placed inside of a stable parent container that can be a sibling to the button container. The reason the jar shakes for any click should be very apparent when looking at the selectors used.
